# Generated by Django 6.0.7 on 2026-07-23 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_location', models.CharField(max_length=255)),
                ('pickup', models.CharField(max_length=255)),
                ('dropoff', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField()),
                ('cycle_hours_used', models.FloatField(default=0.0)),
                ('cycle_limit', models.IntegerField(default=70)),
                ('events_json', models.JSONField(default=list)),
                ('daily_logs_json', models.JSONField(default=list)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
