# Generated by Django 6.0.7 on 2026-07-23 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='route_geojson',
            field=models.JSONField(default=dict),
        ),
    ]
